services:
  backend:
    build: 
      context: ../Backend
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ../Backend/:/var/www/html
    depends_on:
      - db
    networks:
      - weft-network
  frontend:
    build: 
      context: ../Frontend
      dockerfile: Dockerfile
    container_name: react
    volumes:
      - ../Frontend/:/app
    depends_on:
      - backend
    networks:
      - weft-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../Backend/public:/var/www/html/public
      - ../Frontend/dist:/var/www/frontend/dist
    depends_on:
      - backend
      - frontend
    networks:
      - weft-network

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - weft-network
    ports:
      - "3307:3306"

networks: 
  weft-network:
    driver: bridge

volumes:
  db_data:
    driver: local
